### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by RobyRemzy** [Monogramm/docker-dolibarr#22]
hi i'm having some problems running your docker-compose with nginx / psql
it seems nginx can't start here the error message:

```bash
ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/user/file/doli_docker/nginx.conf\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/621e92d392f84cace81030a850e913252b84e10b5d451a22d45a8c447dd59f8a\\\" at \\\"/var/lib/docker/aufs/mnt/621e92d392f84cace81030a850e913252b84e10b5d451a22d45a8c447dd59f8a/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

here my docker-compose very little adjusted from the README

```yml
version: '2'

volumes:
  dolibarr_html:
  dolibarr_docs:
  dolibarr_db:

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - "POSTGRES_DB=dolibarr"
      - "POSTGRES_USER=dolibarr"
      - "POSTGRES_PASSWORD=ok"
    volumes:
      - dolibarr_db:/var/lib/postgresql/data

  dolibarr:
    image: monogramm/docker-dolibarr:8.0.3-php7.1-fpm
    depends_on:
      - postgres
    ports:
      - "80:80"
    environment:
      - "DOLI_DB_TYPE=pgsql"
      - "DOLI_DB_HOST=postgres"
      - "DOLI_DB_PORT=5432"
      - "DOLI_DB_NAME=dolibarr"
      - "DOLI_DB_USER=dolibarr"
      - "DOLI_DB_PASSWORD=ok"
    volumes:
      - dolibarr_html:/var/www/html
      - dolibarr_docs:/var/www/documents

  web:
    image: nginx
    ports:
      - "8080:80"
    links:
      - dolibarr
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - dolibarr
    restart: always
```

**Comment by madmath03** [comment]
Hello,

This might be a silly question, but is your `/home/user/file/doli_docker/nginx.conf` file at this location and with the valid permissions ?

Can you check if `/home/user/file/doli_docker/` directory does not contain `nginx.conf` as directory?
Try with
```
cat /home/user/file/doli_docker/nginx.conf
```

**Comment by RobyRemzy** [comment]
not silly at all! indeed i have to create the nginx.conf.
I'm used to nginx but can you give me a hint on the conf

```nginx
server {
    listen 80;
    listen [::]:80;
    server_name localhost www.localhost;

    root /;
    index index.php index.html index.htm;


    location / {
        try_files $uri $uri/ /index.php;
    }
}
```

should we config the vhost or what should go inside this nginx.conf ?
i'm very new to docker, 
thanks for any help

**Comment by RobyRemzy** [comment]
Hey,
So after some reworks of the docker-compose.yml and the setup of nginx i came here to share. I just find your Base version - FPM with PostgreSQL section of your Readme file a bit misleading some way.

here my docker-compose.yml (sorry for the few customisations with dirs and files)

```yml
version: '2'

services:

  dolinginx:
    image: nginx:latest
    container_name: dolinginx
    ports:
      - '80:80'
      # - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./dolifpm:/var/www/html
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    links:
      - dolifpm
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=dolifpm:9000 # same as dolibarr container name
    restart: always

  dolipgsql:
    image: postgres:latest
    container_name: dolipgsql
    volumes:
      - ./dolipgsql:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=dolibarr"
      - "POSTGRES_USER=dolibarr"
      - "POSTGRES_PASSWORD=dolibarr"
    restart: always

  dolifpm:
    image: monogramm/docker-dolibarr:8.0.3-php7.1-fpm
    container_name: dolifpm
    volumes:
      - ./dolifpm:/var/www/html
      # - ./dolifpm/html:/var/www/html
      # - ./dolifpm/documents:/var/www/documents
    environment:
      - "DOLI_DB_TYPE=pgsql"
      - "DOLI_DB_HOST=dolipgsql" # same as pgsql container name
      - "DOLI_DB_PORT=5432"
      - "DOLI_DB_NAME=dolibarr"  # same as pgsql POSTGRES_DB env name
      - "DOLI_DB_USER=dolibarr"  # same as pgsql POSTGRES_USER env name
      - "DOLI_DB_PASSWORD=dolibarr"  # same as pgsql POSTGRES_PASSWORD env name
    links:
      - dolipgsql
    restart: always
```

here the nginx site.conf

```nginx
server {
    listen 80;
    server_name ${NGINX_HOST};

    root /var/www/html;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass dolifpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

feel free to close the issue, have a good one and thanks for those dolibarr images :beer:
