### ISSUE TITLE
With postgres adapter, we need create_user to be `true`

### ISSUE THREAD

**Issue by sebabouche** [Monogramm/docker-dolibarr#32]
## Describe the bug
I've almost suceeded to install **Dolibarr** with **postgres**. But always experiencing problems because all the fields are disabled during Dolibarr install process.

I 've found a workaround: I manually overwrite `dolibarr_html/install/dolibarr_html/install/install.forced.php` with `$force_install_createuser = true;` but that would be a lot of work to perform on a remote server.

### Run `docker-compose up` with this `docker-compose.yml`:
```
version: "3.1"

services:
  db:
    image: postgres:9-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg-init-scripts/:/docker-entrypoint-initdb.d/
      - ./database:/var/lib/postgresql/data

  dolibarr:
    image: monogramm/docker-dolibarr:9.0-apache
    restart: always
    depends_on:
      - db
    ports:
      - "9000:80"
    environment:
      DOLI_DB_TYPE: pgsql
      DOLI_DB_HOST: db # same as mysql container name
      DOLI_DB_PORT: 5432
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_DB_ROOT_LOGIN: postgres
      DOLI_DB_ROOT_PASSWORD: postgres
      DOLI_ADMIN_LOGIN: admin
      DOLI_URL_ROOT: http://localhost:9000
    volumes:
      - ./dolibarr_html:/var/www/html
      - ./dolibarr_docs:/var/www/documents
      - ./dolibarr_scripts:/var/www/scripts
```

### Go to [localhost:9000/install](localhost:9000/install)
- click next
- all fields are greyed / disabled

## Steps to reproduce second attempt (with a `Dockerfile`):
Here I tried to replace the file `install.forced.php ` with a copy where `$force_install_createuser` is **true**.

#### docker-compose
```
version: "3.1"

services:
  db:
    image: postgres:9-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg-init-scripts/:/docker-entrypoint-initdb.d/
      - ./database:/var/lib/postgresql/data

  dolibarr:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "9000:80"
    environment:
      DOLI_DB_TYPE: pgsql
      DOLI_DB_HOST: db # same as mysql container name
      DOLI_DB_PORT: 5432
      DOLI_DB_NAME: dolibarr # same as mysql MYSQL_DATABASE env name
      DOLI_DB_USER: dolibarr # same as mysql MYSQL_USER env name
      DOLI_DB_PASSWORD: dolibarr # same as mysql MYSQL_PASSWORD env name
      DOLI_DB_ROOT_LOGIN: postgres
      DOLI_DB_ROOT_PASSWORD: postgres
      DOLI_ADMIN_LOGIN: admin
      DOLI_URL_ROOT: http://localhost:9000
    volumes:
      - ./dolibarr_html:/var/www/html
      - ./dolibarr_docs:/var/www/documents
      - ./dolibarr_scripts:/var/www/scripts
```
#### Dockerfile
```
FROM monogramm/docker-dolibarr:9.0-apache

COPY override/install.forced.php /var/www/html/install/install.forced.php/
```

## Expected behavior
- Ability to control forced installation.
- OR would be great to have an environment variable to change `$force_install_createuser` (and maybe `$force_install_createdatabase` so that we can handle db directly in the db container.

## Docker (please complete the following information):
- Docker version 18.09.2, build 6247962
- Docker-compose version: docker-compose version 1.23.2, build 1110ad01

## Desktop:
 - OS: Mac OS Mojave 10.14.3

**Comment by madmath03** [comment]
Thanks for reporting this issue and even providing a PR for it 👍 

I agree that it might be a good idea to allow changing the "_createuser_" behavior but I do not agree with the "_createdatabase_" since your docker-compose example is not appropriate for a postgres setup and it's already possible.

Since you still left the MYSQL comments in your docker-compose, I can see that you mixed the MYSQL sample config with the PGSQL one, but if you check the [FPM/PostgreSQL section](https://github.com/Monogramm/docker-dolibarr#base-version---fpm-with-postgresql) again, or even the official [PostgreSQL docker](https://hub.docker.com/_/postgres), you will see you're supposed to use `POSTGRES_USER` and `POSTGRES_DB` for your application, so it should be the same value as `DOLI_DB_NAME` and `DOLI_DB_USER`.

Based on your setup, the *correct* docker-compose would be more like this:
```yml
version: '3.1'

services:
    dolipgsql:
        image: postgres:9-alpine
        container_name: dolipgsql
        restart: always
    volumes:
        - ./pg-init-scripts/:/docker-entrypoint-initdb.d/
        - ./database:/var/lib/postgresql/data
    environment:
        - "POSTGRES_DB=dolibarr"
        - "POSTGRES_USER=dolibarr"
        - "POSTGRES_PASSWORD=dolibarr"

    dolibarr:
        image: monogramm/docker-dolibarr:9.0-apache
        container_name: dolibarr
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - dolipgsql
        links:
            - dolipgsql
        volumes:
            - ./dolibarr_html:/var/www/html
            - ./dolibarr_docs:/var/www/documents
            - ./dolibarr_scripts:/var/www/scripts
        environment:
            - "DOLI_DB_TYPE=pgsql"
            - "DOLI_DB_HOST=dolipgsql" # same as pgsql container name
            - "DOLI_DB_PORT=5432"
            - "DOLI_DB_NAME=dolibarr" # same as pgsql POSTGRES_DB env name
            - "DOLI_DB_USER=dolibarr" # same as pgsql POSTGRES_USER env name
            - "DOLI_DB_PASSWORD=dolibarr" # same as pgsql POSTGRES_PASSWORD env name
            - "DOLI_ADMIN_LOGIN=admin"
            - "DOLI_URL_ROOT=http://localhost:8080"
```
**Side note**: I do not advise you to redirect port 80 of Apache to 9000, which is the default PHP FPM port... that's really confusing.

Also, regarding the possibility to set the "_createdatabase_" behavior, it's kind of already the case since the only reason to set `DOLI_DB_ROOT_LOGIN` is to let Dolibarr's container create the database, so I do not think that `DOLI_DB_CREATE_DB` you suggested is needed.

I'm okay with merging a PR which will allow to set the "_createuser_" though.

**Comment by sebabouche** [comment]
Thank you for the precise answer and the repo which is very useful.

I will do another PR with just the `DOLI_DB_CREATE_USER` env var and keep smart automatic database creation as soon as `DOLI_DB_ROOT_LOGIN` is provided.

I had had in mind a project where I would have one `postgres` container and multiple Dolibarr instances, that's why I wanted to keep a separate postgres superadmin with full privileges.

What I finally did was create the Dolibarr user within the `postgres` container by providing an sql file inside a `pg-init-scripts` folder ([described here, paragraph](https://hub.docker.com/_/postgres/).

### `pg-init-scripts/init.sql`:
```
CREATE DATABASE dolibarr;
CREATE USER dolibarr WITH ENCRYPTED PASSWORD 'dolibarr';
GRANT ALL PRIVILEGES ON DATABASE dolibarr TO dolibarr;
```

### `docker-compose.yml`
```
version: "3.1"

services:
  db:
    image: postgres:9-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg-init-scripts/:/docker-entrypoint-initdb.d/
      - ./database:/var/lib/postgresql/data

  dolibarr:
    image: monogramm/docker-dolibarr:9.0-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DOLI_DB_TYPE: pgsql
      DOLI_DB_HOST: db
      DOLI_DB_PORT: 5432
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_ADMIN_LOGIN: admin
      DOLI_URL_ROOT: http://localhost:8080
    volumes:
      - ./dolibarr_html:/var/www/html
      - ./dolibarr_docs:/var/www/documents
      - ./dolibarr_scripts:/var/www/scripts
```

**Comment by madmath03** [comment]
For information, `DOLI_DB_ROOT_LOGIN` is already available and documented [here](https://github.com/Monogramm/docker-dolibarr#doli_db_root_login) 😉 

I will review and merge your PR for `DOLI_DB_CREATE_USER` as soon as I can.


Regarding your use case, even if that's technically possible, I'm not sure that's a good idea since it kind of goes against Docker micro-services philosophy.

For instance, if you use one Postgres instance for several applications and need to restart this _main_ postgres container (image update for instance), then all your applications will be down at the same time...
The usual suggestion for such a scenario would be to duplicate the docker-compose I shared for each of your Dolibarr instance you want to run. You could even use an .env file to identify them more easily:
```sh
# TODO Update ID for each instance
DOLIBARR_INSTANCE_ID=0001
```
```yml
version: "3.1"

services:
    dolipgsql:
        image: postgres:9-alpine
        container_name: dolipgsql_${DOLIBARR_INSTANCE_ID}
        # ...

    dolibarr:
        image: monogramm/docker-dolibarr:9.0-apache
        container_name: dolibarr_${DOLIBARR_INSTANCE_ID}
        # ...
        environment:
            - "DOLI_DB_TYPE=pgsql"
            - "DOLI_DB_HOST=dolipgsql_${DOLIBARR_INSTANCE_ID}"
        # ...
```

If your reason for such a use case is to provide a central administration application which would only need to connect to one postgres host, I would suggest you look if it's possible to configure this application to connect to several postgres instances.

Beware that this is just my opinion and I might be missing some information that do not even concern me, so feel free to do as you think is best for you.
