### ISSUE TITLE
Failed to include_once("./core/db/mysqli.class.php") - First install on v11.0-fpm

### ISSUE THREAD

**Issue by ThomasVuillaume** [Monogramm/docker-dolibarr#57]
**Describe the bug**
When I go to the *first installation* step1 and clic on continue, I have the error `Failed to include_once("./core/db/mysqli.class.php")`

**To Reproduce**
1. my_configured_host/install/
2. All pre-requisite are OK (see screenshot)
3. Click on "first install" as it is a first install, and leave all parameters (as edition is disabled anyway, see second screenshot)
4. See error (see third screenshot)

The architecture I use is the following : I'm on a local Windows 10, on which an Ubuntu 18 VM is running. On this VM, I have two docker-compose stacks : the first one is Ngnix, the second one is Dolibarr-MariaDB-phpmyadmin. On the Windows machine an entry is added to the hosts file so that "gestion.cse.vm.local" points to localhost, and  port 3000 on Windows  is forwarded to the port 443 of the VM. This way, on a browser on Windows, I can access Dolibarr at `https://gestion.cse.vm.local:3000`

Here are the docker-compose : 

NGNIX : 

```
version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./volumes/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/etc/nginx/certs:/etc/nginx/certs
      - dolibarr-html:/var/www/html/dolibarr
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=cse.vm.local
      - NGINX_CGI=php-fpm-dolibarr:9000
    networks:
      proxy:
        aliases:
          - nginx
    restart: unless-stopped

networks:
  proxy:
    external:
      name: dolibarr_nginx_proxy
volumes:
  dolibarr-html:
    external:
      name: dolibarr_dolibarr-html
```

NGNIX-APP-CONF

```
server {
    listen nginx:80;
    server_name cse.vm.local;

    return 301 https://$host$request_uri;
}

server {
    listen nginx:443 ssl;
    server_name gestion.cse.vm.local;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

	root /var/www/html/dolibarr;
	index index.html index.htm index.php;
	
	sendfile on;

	location / {
        try_files $uri $uri/ index.php;
    }

	# Deal with PHP files in FastCGI
	location ~ [^/]\.php(/|$) {
		fastcgi_split_path_info ^(.+?\.php)(/.*)$;
		if (!-f $document_root$fastcgi_script_name) {
			return 404;
		}

		fastcgi_pass   php-fpm-dolibarr:9000;
		fastcgi_index  index.php;

		include fastcgi_params;

		# Mitigate https://httpoxy.org/ vulnerabilities
		fastcgi_param HTTP_PROXY "";
		fastcgi_intercept_errors off;
		fastcgi_connect_timeout 30s;
		fastcgi_send_timeout 300s;
		fastcgi_read_timeout 600s;

		# Removing the leading slash from $fastcgi_script_name allows it to be interpreted relative to php-fpm.conf's `chdir` directive
		set $filename "index.php";
		if ( $fastcgi_script_name ~ "^/+(.*)$" ) {
			set $filename $1;
		}
		fastcgi_param SCRIPT_FILENAME $filename;
		fastcgi_param PATH_INFO       $fastcgi_path_info;
		fastcgi_param PATH_TRANSLATED $fastcgi_path_info;
	}

	location /api {
        if ( !-e $request_filename) {
            rewrite ^.* /api/index.php last;
        }
    }

}

```

DOLIBARR

```
version: '3.7'

services:
    mariadb:
      image: mariadb:latest
      volumes:
        - dolibarr_db:/var/lib/mysql
      command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=dolibarr
          - MYSQL_USER=dolibarr
          - MYSQL_PASSWORD=dolibarr
      ports:
          - "3306:3306"
      networks:
        - backend
        - nginx_proxy
    
    phpmyadmin:
      depends_on:
        - mariadb
      image: phpmyadmin/phpmyadmin
      ports:
        - '8080:80'
      environment:
        - PMA_HOST=mariadb
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - backend
          
    php-fpm-dolibarr:
      image: monogramm/docker-dolibarr:11.0-fpm
      volumes:
        - dolibarr-html:/var/www/html
        - dolibarr-documents:/var/www/documents
        - dolibarr-scripts:/var/www/scripts
      environment:
          - DOLI_DB_HOST=mariadb
          - DOLI_DB_USER=dolibarr
          - DOLI_DB_PASSWORD=dolibarr
          - DOLI_DB_NAME=dolibarr
      ports:
          - "9000:9000"
      depends_on:
          - mariadb
      networks:
        - backend
        - nginx_proxy

volumes:
  dolibarr-html:
  dolibarr-documents:
  dolibarr-scripts:
  dolibarr_db:

# See https://docs.docker.com/compose/networking/
networks:
  nginx_proxy:
    driver: bridge
  backend:
```

**Expected behavior**
Well, no error I guess.

**Screenshots**
![image](https://user-images.githubusercontent.com/25711113/78424022-e7746f80-766a-11ea-96fe-3f1e84e99237.png)

![image](https://user-images.githubusercontent.com/25711113/78424031-08d55b80-766b-11ea-9d62-cb417baa9603.png)

![image](https://user-images.githubusercontent.com/25711113/78424055-2e626500-766b-11ea-8a94-116576d2955e.png)

**Docker (please complete the following information):**
 - Docker / Docker-compose Version:  Docker version 19.03.8, build afacb8b7f0 // docker-compose version 1.24.1, build 4667896b  
 - Image monogramm/docker-dolibarr:11.0-fpm

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser Any
 - Version Any

**Additional context**
None
