### ISSUE TITLE
Cron not starting automatically

### ISSUE THREAD

**Issue by stephan192** [Monogramm/docker-dolibarr#67]
**Describe the bug**
I'm running your image via a compose file on a three node docker swarm which uses GlusterFS as shared filesystem so that it doesn't matter on which node the service gets deployed. MariaDB is deployed separately via an extra compose file.
I bind mount all the required folders (`/var/www/html`, `/var/www/documents`, ...) from the shared GlusterFS. Additionally i bind mount a file from the shared GlusterFS to `/etc/crontab` like you suggested in #45.

The problem is:
Whenever i deploy the compose file via `sudo docker stack deploy` or the container is redeployed by the swarm manager the container starts but **not** the cron service inside the container.
I always have to manually exec into the container via `sudo docker exec -it <hash> bash` and run `service cron restart` inside the container. After restarting cron inside the container everything works as expected until the container is redeployed.

**compose file:**
```
version: '3.7'

services:
  dolibarr:
    image: monogramm/docker-dolibarr:13.0.1-apache
    volumes:
      - /mnt/gv0/dolibarr/dolibarr/documents:/var/www/documents
      - /mnt/gv0/dolibarr/dolibarr/html:/var/www/html
      - /mnt/gv0/dolibarr/dolibarr/scripts:/var/www/scripts
      - /mnt/gv0/dolibarr/dolibarr/cron/crontab:/etc/crontab
    environment:
      DOLI_AUTO_CONFIGURE: 1
      DOLI_DB_TYPE: mysqli
      DOLI_DB_HOST: dolibarr-mariadb_mariadb
      DOLI_DB_PORT: 3306
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: <pass>
      DOLI_DB_PREFIX: llx_
      DOLI_DB_CHARACTER_SET: utf8
      DOLI_DB_COLLATION: utf8_unicode_ci
      DOLI_ADMIN_LOGIN: admin
      PHP_INI_DATE_TIMEZONE: 'Europe/Berlin'
      PHP_INI_MEMORY_LIMIT: 256M
    networks:
      - dolibarr-network
    ports:
      - '4444:80'

networks:
  dolibarr-network:
    external: true
```

**crontab:**
```
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
*/5 *	* * *	www-data	/var/www/scripts/cron/cron_run_jobs.php <hash> <user> > /var/www/documents/cron_run_jobs.php.log
#

```

**Expected behavior**
Cron should start automatically with the mounted `crontab` whenever the container is deployed/redeployed.

**Docker (please complete the following information):**
- Docker  20.10.5-ce
- monogramm/docker-dolibarr:13.0.1-apache
